## PROYECTO MÓDULO 3 - OPTIMIZACIÓN DEL TALENTO

---------------------------

FASE 1: ANÁLISIS EXPLORATOTIO DE DATOS (EDA)

In [1]:
# PASO 1: Importamos las librerías necesarias

import pandas as pd # Para manipular datos en tablas (DataFrames)
import numpy as np # Para realizar operaciones numéricas

In [2]:
# PASO 2: Cargamos el dataset (archivo .csv) y lo convertimos en un DataFrame de pandas (tabla)

pd.set_option("display.max_columns", None) # Muestra todas las columnas del DataFrame

df_hr = pd.read_csv("hr.csv") 

df_hr.head() # Muestra las primeras 5 filas del DataFrame para verificar que se ha cargado correctamente

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,lABORATORY tECHNICIAN,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,rESEARCH sCIENTIST,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,lABORATORY tECHNICIAN,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0

In [3]:
# PASO 3: Exploramos el dataset para entender su estructura y contenido

df_hr.info() # Muestra la información de nuestro DataFrame: número de filas y columnas + nombre de lascolumnas + valores no nulos + tipos de datos

<class 'pandas.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   str
 2   BusinessTravel            1357 non-null   str
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   str
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   str
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   str
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   str
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   str
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   str
 22  OverTime                  1430 non-null   str
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
dtypes: float64(6), int64(20), str(9)
memory usage: 403.2 KB

In [4]:
# PASO 4: Entender qué representa cada columna

columnas_texto = df_hr.select_dtypes(include=["string"]) # Sacamos todas las columans de tipo 'string' -> Columnas categóricas

columnas_texto.head().T # Transponemos el resultado para verlo mejor (filas pasan a ser columnas y viceversa)

,0,1,2,3,4
Attrition,Yes,No,Yes,No,No
BusinessTravel,Travel_Rarely,Travel_Frequently,Travel_Rarely,Travel_Frequently,Travel_Rarely
Department,Sales,Research & Development,Research & Development,Research & Development,Research & Development
EducationField,Life Sciences,Life Sciences,Other,Life Sciences,Medical
Gender,Female,Male,Male,Female,Male
JobRole,sALES eXECUTIVE,rESEARCH sCIENTIST,lABORATORY tECHNICIAN,rESEARCH sCIENTIST,lABORATORY tECHNICIAN
MaritalStatus,Single,Married,Single,Married,Married
Over18,Y,Y,Y,Y,Y
OverTime,Yes,No,Yes,Yes,No

In [5]:
columnas_numeros = df_hr.select_dtypes(include=["number"]) # Sacamos todas las columnas de tipo 'number' -> Columnas numéricas

columnas_numeros.head().T

                                0        1       2        3        4
Age                          41.0     49.0    37.0     33.0     27.0
DailyRate                  1102.0    279.0  1373.0   1392.0    591.0
DistanceFromHome              1.0      8.0     2.0      3.0      2.0
Education                     2.0      1.0     2.0      4.0      1.0
EmployeeCount                 1.0      1.0     1.0      1.0      1.0
EmployeeNumber                1.0      2.0     4.0      5.0      7.0
EnvironmentSatisfaction       2.0      3.0     4.0      4.0      1.0
HourlyRate                   94.0     61.0    92.0     56.0     40.0
JobInvolvement                3.0      2.0     2.0      3.0      3.0
JobLevel                      2.0      2.0     1.0      1.0      1.0
JobSatisfaction               4.0      2.0     3.0      3.0      2.0
MonthlyIncome              5993.0   5130.0  2090.0   2909.0   3468.0
MonthlyRate               19479.0  24907.0  2396.0  23159.0  16632.0
NumCompaniesWorked            8.0      1.0     6.0      1.0      9.0
PercentSalaryHike            11.0     23.0    15.0     11.0     12.0
PerformanceRating             3.0      4.0     3.0      3.0      3.0
RelationshipSatisfaction      1.0      4.0     2.0      3.0      4.0
StandardHours                80.0      NaN     NaN     80.0     80.0
StockOptionLevel              0.0      1.0     0.0      0.0      1.0
TotalWorkingYears             8.0     10.0     7.0      8.0      6.0
TrainingTimesLastYear         0.0      3.0     3.0      3.0      3.0
WorkLifeBalance               1.0      3.0     3.0      3.0      3.0
YearsAtCompany                6.0     10.0     0.0      8.0      2.0
YearsInCurrentRole            4.0      7.0     0.0      7.0      2.0
YearsSinceLastPromotion       0.0      1.0     0.0      3.0      2.0
YearsWithCurrManager          5.0      7.0     0.0      0.0      2.0

In [ ]:
df_hr.nunique().sort_values(ascending=False) # Muestra qué columna tienene el mismo valor en todas las filas en orden ascendente

EmployeeNumber              1470
MonthlyRate                 1427
MonthlyIncome               1336
DailyRate                    886
HourlyRate                    71
Age                           43
TotalWorkingYears             40
YearsAtCompany                37
DistanceFromHome              29
YearsInCurrentRole            19
YearsWithCurrManager          18
YearsSinceLastPromotion       16
PercentSalaryHike             15
NumCompaniesWorked            10
JobRole                        9
TrainingTimesLastYear          7
EducationField                 6
JobLevel                       5
Education                      5
EnvironmentSatisfaction        4
WorkLifeBalance                4
StockOptionLevel               4
RelationshipSatisfaction       4
MaritalStatus                  4
JobSatisfaction                4
JobInvolvement                 4
Department                     3
BusinessTravel                 3
PerformanceRating              2
OverTime                       2
Attrition                      2
Gender                         2
StandardHours                  1
Over18                         1
EmployeeCount                  1
dtype: int64

In [8]:
# PASO 5: Buscar valores nulos

df_hr.isna().sum().sort_values(ascending=False) # Muestra el número de valores nulos que hay por columna

StandardHours               164
YearsWithCurrManager        148
MaritalStatus               132
BusinessTravel              117
TrainingTimesLastYear        88
Age                          73
EducationField               58
OverTime                     44
JobSatisfaction              29
Department                   29
MonthlyIncome                14
YearsAtCompany                0
WorkLifeBalance               0
YearsInCurrentRole            0
TotalWorkingYears             0
Over18                        0
YearsSinceLastPromotion       0
RelationshipSatisfaction      0
PerformanceRating             0
PercentSalaryHike             0
StockOptionLevel              0
DailyRate                     0
NumCompaniesWorked            0
Attrition                     0
JobRole                       0
JobLevel                      0
JobInvolvement                0
HourlyRate                    0
Gender                        0
EnvironmentSatisfaction       0
EmployeeNumber                0
EmployeeCount                 0
Education                     0
DistanceFromHome              0
MonthlyRate                   0
dtype: int64

In [9]:
round(df_hr.isna().sum().sort_values(ascending=False)/df_hr.shape[0]*100,2) # Muestra el número de nulos en porcentaje

StandardHours               11.13
YearsWithCurrManager        10.04
MaritalStatus                8.96
BusinessTravel               7.94
TrainingTimesLastYear        5.97
Age                          4.95
EducationField               3.93
OverTime                     2.99
JobSatisfaction              1.97
Department                   1.97
MonthlyIncome                0.95
YearsAtCompany               0.00
WorkLifeBalance              0.00
YearsInCurrentRole           0.00
TotalWorkingYears            0.00
Over18                       0.00
YearsSinceLastPromotion      0.00
RelationshipSatisfaction     0.00
PerformanceRating            0.00
PercentSalaryHike            0.00
StockOptionLevel             0.00
DailyRate                    0.00
NumCompaniesWorked           0.00
Attrition                    0.00
JobRole                      0.00
JobLevel                     0.00
JobInvolvement               0.00
HourlyRate                   0.00
Gender                       0.00
EnvironmentSatisfaction      0.00
EmployeeNumber               0.00
EmployeeCount                0.00
Education                    0.00
DistanceFromHome             0.00
MonthlyRate                  0.00
dtype: float64

In [11]:
# PASO 5: Revisar duplicados

df_hr.duplicated().sum() # Muestra cuántos valores hay duplicados -> Copia/s

np.int64(4)

In [12]:
df_hr[df_hr.duplicated()] # Observamos las 4 filas repetidas

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1470,28.0,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,4,Male,84,3,2,sALES eXECUTIVE,1.0,Single,8463.0,23490,0,Y,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1471,53.0,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,4,Female,57,4,2,mANUFACTURING dIRECTOR,1.0,Divorced,4450.0,26250,1,Y,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,hUMAN rESOURCES,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,rESEARCH sCIENTIST,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0

In [14]:
df_hr[df_hr.duplicated(keep=False)] # Comprobamos que existen 4 originales y 1 copia por cada origina -> Nos fijamos en los índices para saber cual es la copia

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
67,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,rESEARCH sCIENTIST,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0
184,53.0,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,4,Female,57,4,2,mANUFACTURING dIRECTOR,1.0,Divorced,4450.0,26250,1,Y,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
1041,28.0,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,4,Male,84,3,2,sALES eXECUTIVE,1.0,Single,8463.0,23490,0,Y,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1222,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,hUMAN rESOURCES,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1470,28.0,No,Travel_Rarely,866,Sales,5,3,Medical,1,1469,4,Male,84,3,2,sALES eXECUTIVE,1.0,Single,8463.0,23490,0,Y,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1471,53.0,No,Travel_Rarely,1084,Research & Development,13,2,Medical,1,250,4,Female,57,4,2,mANUFACTURING dIRECTOR,1.0,Divorced,4450.0,26250,1,Y,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
1472,24.0,Yes,Travel_Rarely,240,Human Resources,22,1,Human Resources,1,1714,4,Male,58,1,1,hUMAN rESOURCES,3.0,Married,1555.0,11585,1,Y,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,1,86,2,Male,59,3,3,rESEARCH sCIENTIST,1.0,Divorced,9724.0,18787,2,Y,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0

In [16]:
# PASO 6: Estadísticas descriptivas 

df_hr.describe(include="str").T # Muestra estadísticas descriptivas de las columnas categóricas: número de valores únicos + valor más frecuente + su frecuencia

               count unique                     top  freq
Attrition       1474      2                      No  1236
BusinessTravel  1357      3           Travel_Rarely   955
Department      1445      3  Research & Development   941
EducationField  1416      6           Life Sciences   582
Gender          1474      2                    Male   885
JobRole         1474      9        sALES eXECUTIVE    327
MaritalStatus   1342      4                 Married   604
Over18          1474      1                       Y  1474
OverTime        1430      2                      No  1025

In [ ]:
df_hr.describe().T # Muestra estadísticas descriptivas de las columnas numéricas: media + desviación típica + mínima + percentiles (mediana) + máxima

,count,mean,std,min,25%,50%,75%,max
Age,1401.0,36.944325,9.105009,18.0,30.00,36.0,43.00,60.0
DailyRate,1474.0,802.702171,403.539530,102.0,465.00,803.0,1157.00,1499.0
DistanceFromHome,1474.0,9.199457,8.104266,1.0,2.00,7.0,14.00,29.0
Education,1474.0,2.911126,1.024267,1.0,2.00,3.0,4.00,5.0
EmployeeCount,1474.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0
EmployeeNumber,1474.0,1024.471506,602.421193,1.0,488.75,1020.5,1555.75,2068.0
EnvironmentSatisfaction,1474.0,2.723881,1.093280,1.0,2.00,3.0,4.00,4.0
HourlyRate,1474.0,65.887381,20.310444,30.0,48.00,66.0,83.75,100.0
JobInvolvement,1474.0,2.729986,0.712861,1.0,2.00,3.0,3.00,4.0
JobLevel,1474.0,2.063772,1.106055,1.0,1.00,2.0,3.00,5.0
JobSatisfaction,1445.0,2.728720,1.106409,1.0,2.00,3.0,4.00,4.0
MonthlyIncome,1460.0,6497.448630,4706.059294,1009.0,2909.00,4907.0,8377.00,19999.0
MonthlyRate,1474.0,14328.611940,7120.225285,2094.0,8054.50,14248.5,20465.75,26999.0
NumCompaniesWorked,1474.0,2.688602,2.496443,0.0,1.00,2.0,4.00,9.0
PercentSalaryHike,1474.0,15.206920,3.659274,11.0,12.00,14.0,18.00,25.0
PerformanceRating,1474.0,3.153324,0.360422,3.0,3.00,3.0,3.00,4.0
RelationshipSatisfaction,1474.0,2.713704,1.080338,1.0,2.00,3.0,4.00,4.0
StandardHours,1310.0,80.000000,0.000000,80.0,80.00,80.0,80.00,80.0
StockOptionLevel,1474.0,0.794437,0.851784,0.0,0.00,1.0,1.00,3.0
TotalWorkingYears,1474.0,11.274084,7.785972,0.0,6.00,10.0,15.00,40.0
TrainingTimesLastYear,1386.0,2.797980,1.296882,0.0,2.00,3.0,3.00,6.0
WorkLifeBalance,1474.0,2.761872,0.705625,1.0,2.00,3.0,3.00,4.0
YearsAtCompany,1474.0,6.996608,6.122920,0.0,3.00,5.0,9.00,40.0
YearsInCurrentRole,1474.0,4.221845,3.622032,0.0,2.00,3.0,7.00,18.0
YearsSinceLastPromotion,1474.0,2.183175,3.219356,0.0,0.00,1.0,3.00,15.0
YearsWithCurrManager,1326.0,4.061840,3.517603,0.0,2.00,3.0,7.00,17.0

FASE 2: TRANSFORMACIÓN DE DATOS

In [ ]:
 # Borramos  los duplicados despues de comprobar

df_hr=df_hr.drop_duplicates()

IndentationError: unexpected indent (3089742543.py, line 2)

In [36]:
df_hr["TotalWorkingYears"].unique()

array([ 8, 10,  7,  6, 12,  1, 17,  5,  3, 31, 13,  0, 26, 24, 22,  9, 19,
        2, 23, 14, 15,  4, 29, 28, 21, 25, 20, 11, 16, 37, 38, 30, 40, 18,
       36, 34, 32, 33, 35, 27])

In [ ]:
df_hr=df_hr.drop_duplicates()

In [ ]:
df_hr.head().T

,0,1,2,3,4
Age,41.0,49.0,37.0,33.0,27.0
Attrition,Yes,No,Yes,No,No
BusinessTravel,Travel_Rarely,Travel_Frequently,Travel_Rarely,Travel_Frequently,Travel_Rarely
DailyRate,1102,279,1373,1392,591
Department,Sales,Research & Development,Research & Development,Research & Development,Research & Development
DistanceFromHome,1,8,2,3,2
Education,2,1,2,4,1
EducationField,Life Sciences,Life Sciences,Other,Life Sciences,Medical
EmployeeCount,1,1,1,1,1
EmployeeNumber,1,2,4,5,7
EnvironmentSatisfaction,2,3,4,4,1
Gender,Female,Male,Male,Female,Male
HourlyRate,94,61,92,56,40
JobInvolvement,3,2,2,3,3
JobLevel,2,2,1,1,1
JobRole,sALES eXECUTIVE,rESEARCH sCIENTIST,lABORATORY tECHNICIAN,rESEARCH sCIENTIST,lABORATORY tECHNICIAN
JobSatisfaction,4.0,2.0,3.0,3.0,2.0
MaritalStatus,Single,Married,Single,Married,Married
MonthlyIncome,5993.0,5130.0,2090.0,2909.0,3468.0
MonthlyRate,19479,24907,2396,23159,16632
NumCompaniesWorked,8,1,6,1,9
Over18,Y,Y,Y,Y,Y
OverTime,Yes,No,Yes,Yes,No
PercentSalaryHike,11,23,15,11,12
PerformanceRating,3,4,3,3,3
RelationshipSatisfaction,1,4,2,3,4
StandardHours,80.0,NaN,NaN,80.0,80.0
StockOptionLevel,0,1,0,0,1
TotalWorkingYears,8,10,7,8,6
TrainingTimesLastYear,0.0,3.0,3.0,3.0,3.0
WorkLifeBalance,1,3,3,3,3
YearsAtCompany,6,10,0,8,2
YearsInCurrentRole,4,7,0,7,2
YearsSinceLastPromotion,0,1,0,3,2
YearsWithCurrManager,5.0,7.0,0.0,0.0,2.0

In [24]:
#vamos a poner todo el dataframe en minusculas. hay que poner la primera letra en mayuscula.
# aqui pasamos las columnas a minusculas.(fase 2)
for col in df_hr.select_dtypes(include="object"):df_hr[col]=df_hr[col].str.lower()#recorremos todas las columnas y las convertimos a minusculas. solo para texto.

C:\Users\Janira\AppData\Local\Temp\ipykernel_12264\3630780856.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_hr.select_dtypes(include="object"):df_hr[col]=df_hr[col].str.lower()#recorremos todas las columnas y las convertimos a minusculas. solo para texto.

In [25]:
df_hr.head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,yes,travel_rarely,1102,sales,1,2,life sciences,1,1,...,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,no,travel_frequently,279,research & development,8,1,life sciences,1,2,...,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,yes,travel_rarely,1373,research & development,2,2,other,1,4,...,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,no,travel_frequently,1392,research & development,3,4,life sciences,1,5,...,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,no,travel_rarely,591,research & development,2,1,medical,1,7,...,4,80.0,1,6,3.0,3,2,2,2,2.0

In [ ]:
#vamos a ver el porcentaje  de desercion.
df_hr["attrition"].value_counts(normalize=True) *100#hay un 0.16 de desercion tampoco es tanto, comparado con los que si permanecen en la empresa.

attrition
no     83.85346
yes    16.14654
Name: proportion, dtype: float64

In [ ]:
#vamos a eliminar columnas redundantes. //  dejo la de mayor de 18 años por si entrara algun menor aunque en este analisis actualmente es redundante tambien.
#eliminamos standardhours todas son 80h ,
df_1 = df_hr.drop(['employeecount', 'standardhours'], axis=1, errors='ignore')

In [ ]:
df_1.columns # compruebo que se eliminaron

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'over18',
       'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'stockoptionlevel', 'totalworkingyears',
       'trainingtimeslastyear', 'worklifebalance', 'yearsatcompany',
       'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager'],
      dtype='str')

FASE 3: VISUALIZACIÓN DE DATOS

FASE 4: DISEÑO DE BBDD E INSERCCIÓN DE LOS DATOS